// Code generated by MockGen. DO NOT EDIT.
// Source: internal/payment/repository/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/payment/repository/init.go -destination=_mock/payment/mock_repository.go -package=mockpayment -mock_names=Payment=MockPaymentRepository
//

// Package mockpayment is a generated GoMock package.
package mockpayment

import (
	context "context"
	model "parkir-pintar/services/payment/internal/payment/model"
	apperror "parkir-pintar/services/payment/pkg/apperror"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}

// Exec mocks base method.
func (m *MockDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// QueryRow mocks base method.
func (m *MockDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDB)(nil).QueryRow), varargs...)
}

// MockPaymentRepository is a mock of Payment interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentRepository) CreatePayment(ctx context.Context, payment *model.Payment) (*model.Payment, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, payment)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentRepositoryMockRecorder) CreatePayment(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentRepository)(nil).CreatePayment), ctx, payment)
}

// GetByID mocks base method.
func (m *MockPaymentRepository) GetByID(ctx context.Context, paymentID string) (*model.Payment, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, paymentID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPaymentRepositoryMockRecorder) GetByID(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPaymentRepository)(nil).GetByID), ctx, paymentID)
}

// GetByIdempotencyKey mocks base method.
func (m *MockPaymentRepository) GetByIdempotencyKey(ctx context.Context, key string) (*model.Payment, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockPaymentRepositoryMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockPaymentRepository)(nil).GetByIdempotencyKey), ctx, key)
}

// GetByReferenceAndType mocks base method.
func (m *MockPaymentRepository) GetByReferenceAndType(ctx context.Context, referenceID string, paymentType model.PaymentType) (*model.Payment, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReferenceAndType", ctx, referenceID, paymentType)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByReferenceAndType indicates an expected call of GetByReferenceAndType.
func (mr *MockPaymentRepositoryMockRecorder) GetByReferenceAndType(ctx, referenceID, paymentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReferenceAndType", reflect.TypeOf((*MockPaymentRepository)(nil).GetByReferenceAndType), ctx, referenceID, paymentType)
}

// UpdateQRCodeURL mocks base method.
func (m *MockPaymentRepository) UpdateQRCodeURL(ctx context.Context, paymentID, qrCodeURL string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQRCodeURL", ctx, paymentID, qrCodeURL)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// UpdateQRCodeURL indicates an expected call of UpdateQRCodeURL.
func (mr *MockPaymentRepositoryMockRecorder) UpdateQRCodeURL(ctx, paymentID, qrCodeURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQRCodeURL", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateQRCodeURL), ctx, paymentID, qrCodeURL)
}

// UpdateStatus mocks base method.
func (m *MockPaymentRepository) UpdateStatus(ctx context.Context, paymentID string, status model.PaymentStatus, gatewayRef string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, paymentID, status, gatewayRef)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdateStatus(ctx, paymentID, status, gatewayRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdateStatus), ctx, paymentID, status, gatewayRef)
}
