// Code generated by MockGen. DO NOT EDIT.
// Source: internal/payment/usecase/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/payment/usecase/init.go -destination=_mock/payment/mock_usecase.go -package=mockpayment -mock_names=Payment=MockPaymentUsecase
//

// Package mockpayment is a generated GoMock package.
package mockpayment

import (
	context "context"
	model "parkir-pintar/services/payment/internal/payment/model"
	apperror "parkir-pintar/services/payment/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentUsecase is a mock of Payment interface.
type MockPaymentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUsecaseMockRecorder
	isgomock struct{}
}

// MockPaymentUsecaseMockRecorder is the mock recorder for MockPaymentUsecase.
type MockPaymentUsecaseMockRecorder struct {
	mock *MockPaymentUsecase
}

// NewMockPaymentUsecase creates a new mock instance.
func NewMockPaymentUsecase(ctrl *gomock.Controller) *MockPaymentUsecase {
	mock := &MockPaymentUsecase{ctrl: ctrl}
	mock.recorder = &MockPaymentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUsecase) EXPECT() *MockPaymentUsecaseMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentUsecase) CreatePayment(ctx context.Context, req model.CreatePaymentRequest) (*model.CreatePaymentResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, req)
	ret0, _ := ret[0].(*model.CreatePaymentResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentUsecaseMockRecorder) CreatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentUsecase)(nil).CreatePayment), ctx, req)
}

// GetPaymentStatus mocks base method.
func (m *MockPaymentUsecase) GetPaymentStatus(ctx context.Context, paymentID string) (*model.GetPaymentStatusResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentStatus", ctx, paymentID)
	ret0, _ := ret[0].(*model.GetPaymentStatusResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetPaymentStatus indicates an expected call of GetPaymentStatus.
func (mr *MockPaymentUsecaseMockRecorder) GetPaymentStatus(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentStatus", reflect.TypeOf((*MockPaymentUsecase)(nil).GetPaymentStatus), ctx, paymentID)
}

// HandleCallback mocks base method.
func (m *MockPaymentUsecase) HandleCallback(ctx context.Context, req model.WebhookCallbackRequest) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, req)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockPaymentUsecaseMockRecorder) HandleCallback(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockPaymentUsecase)(nil).HandleCallback), ctx, req)
}
